---
- hosts: ec2
  become: True
  vars:
    root_user: root
    ec2_user: ec2-user
    ruby_version: 2.3.3
    rbenv_path: /.rbenv/bin:$PATH
    execute_rbenv: /home/{{ ec2_user }}/.rbenv/bin
    nodejs_version: v6.8.1
  roles:
    - ec2-railsenv
    - ec2-nodejs
    - ec2-nginx
