---
- name: Install dependencies for rbenv
  yum: name={{ item }} state=latest
  with_items:
    - git
- name: Install rbenv
  become: False
  become_user: "{{ root_user }}"
  git: repo=git@github.com:rbenv/rbenv.git dest=~/.rbenv accept_hostkey=yes
  register: rbenv_changed
- name: Install dependencies for ruby-build
  become: True
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline
    - zlib
    - libxml2
    - libxml2-devel
    - libxslt-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
    - make
- name: Install ruby-build as rbenv plugin
  become: False
  git: repo=git@github.com:rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build accept_hostkey=yes
- name: Check rbenv installed
  become: False
  shell: "{{ execute_rbenv }}/rbenv -v"
  register: rbenv_installed
- name: enabled ruby-build
  become: True
  become_user: "{{ root_user }}"
  shell: .rbenv/plugins/ruby-build/install.sh
- name: Add $PATH to ~/.bash_profile
  become: True
  lineinfile:
    dest: ~/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
- name: Add eval '(rbenv init -)' to ~/.bash_profile
  become: True
  lineinfile:
    dest: ~/.bash_profile
    line: 'eval "(rbenv init -)"'
- name: reload ~/.bash_profile
  become: True
  shell: echo "source ~/.bash_profile"
- name: Check if ruby {{ ruby_version }} installed or not
  become: False
  shell: "{{ execute_rbenv }}/rbenv versions executable=/bin/bash"
  register: rbenv_versions
- name: Check if rbenv global {{ ruby_version }} or not
  become: False
  shell: "{{ execute_rbenv }}/rbenv global"
  register: rbenv_global
- name: Install Ruby version {{ ruby_version }}
  become: False
  shell: "{{ execute_rbenv }}/rbenv install {{ ruby_version }} executable=/bin/bash"
  tags:
    - ruby_install
  when: (rbenv_versions.stdout_lines[1] != "  {{ ruby_version }}") and (rbenv_global.stdout != "{{ ruby_version }}")
- name: Execute rbenv rehash
  become: False
  shell: "{{ execute_rbenv }}/rbenv rehash"
  when: rbenv_global.stdout != "{{ ruby_version }}"
- name: Change global Ruby version
  become: False
  shell: "{{ execute_rbenv }}/rbenv global {{ ruby_version }}"
  when: rbenv_global.stdout != "{{ ruby_version }}"
- name: Execute rbenv rehash
  become: False
  shell: "{{ execute_rbenv }}/rbenv rehash"
  when: rbenv_global.stdout != "{{ ruby_version }}"
- name: Reload ~/.bash_profile for rbenv
  become: False
  shell: echo "source ~/.bash_profile"
  when: rbenv_global.stdout != "{{ ruby_version }}"
- name: Install dependencies for ImageMagic
  yum: name={{ item }} state=present
  with_items:
    - libjpeg-devel
    - libpng-devel
    - ImageMagick
    - ImageMagick-devel
- name: Install dependencies for Nokogiri
  yum: name={{ item }} state=present
  with_items:
    - patch
- name: Install gem bundler and gem Rails
  become_user: "{{ root_user }}"
  gem: name={{ item }} executable=.rbenv/shims/gem user_install=False
  with_items:
    - bundler
    - rails
- name: Install gem nokogiri
  gem:
    name: nokogiri
    version: 1.7.0
    state: present
    executable: .rbenv/shims/gem
    user_install: False
- name: Execute rbenv rehash
  shell: "{{ execute_rbenv }}/rbenv rehash"
